'use client';

import DashboardLayout from '@/components/DashboardLayout';
import { FileText, Download, Calendar, BarChart3, Award, Filter, Search } from 'lucide-react';
import { MOCK_STUDENT_REPORTS } from '@/lib/mock-data';
import { useAuth } from '@/contexts/AuthContext';

export default function ParentReports() {
  const { user } = useAuth();

  if (!user) return null;

  const handleDownload = (reportId: string) => {
    // Mock download
    const link = document.createElement('a');
    link.href = `/api/reports/${reportId}`;
    link.download = `NIOS-Report-${reportId}.pdf`;
    link.click();
  };

  return (
    <DashboardLayout
      title="Academic Reports"
      subtitle="Downloadable performance analytics and progress evaluations"
    >
      <div className="space-y-12 pb-20">
        {/* Header */}
        <div className="flex flex-col lg:flex-row gap-6 items-start lg:items-center justify-between">
          <div>
            <h1 className="text-3xl font-black text-slate-900 tracking-tight mb-2">Student Reports</h1>
            <p className="text-slate-500 font-medium leading-relaxed max-w-2xl">
              Comprehensive evaluations generated by faculty. All documents are blockchain-verified and tamper-proof.
            </p>
          </div>
          <div className="flex gap-3">
            <button className="px-8 py-4 bg-white border border-slate-100 rounded-xl shadow-sm font-black text-[10px] uppercase tracking-widest hover:shadow-lg transition-all flex items-center gap-2">
              <Filter size={16} /> Filter
            </button>
            <button className="px-8 py-4 bg-slate-900 text-white rounded-xl shadow-xl font-black text-[10px] uppercase tracking-widest hover:bg-black transition-all flex items-center gap-2">
              <Download size={16} /> Bulk Download
            </button>
          </div>
        </div>

        {/* Reports Grid */}
        <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-6">
          {MOCK_STUDENT_REPORTS.map((report) => (
            <div key={report.id} className="group p-8 rounded-xl bg-white border-2 border-slate-100 hover:border-blue-900 hover:shadow-2xl hover:shadow-blue-500/10 transition-all overflow-hidden h-full">
              <div className="absolute inset-0 bg-gradient-to-br from-blue-900/0 via-blue-900/3 to-transparent pointer-events-none" />

              <div className="relative z-10 flex items-start justify-between mb-6">
                <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-emerald-400 to-teal-500 flex items-center justify-center text-white shadow-lg mb-4 shrink-0">
                  <FileText size={20} />
                </div>
                <div className="flex items-center gap-2 opacity-0 group-hover:opacity-100 transition-all ml-4">
                  <button
                    onClick={() => handleDownload(report.id)}
                    className="p-2 bg-white/20 hover:bg-white/30 rounded-lg backdrop-blur-sm text-white transition-all flex items-center justify-center shadow-md"
                    title="Download PDF"
                  >
                    <Download size={16} />
                  </button>
                </div>
              </div>

              <div className="space-y-3">
                <h3 className="text-xl font-black text-slate-900 tracking-tight leading-tight group-hover:text-blue-900 transition-colors line-clamp-2">{report.title}</h3>

                <div className="flex items-center gap-6 text-[10px] font-black text-slate-400 uppercase tracking-widest">
                  <div className="flex items-center gap-1">
                    <Calendar size={12} /> {report.period}
                  </div>
                  <div className="flex items-center gap-1">
                    <BarChart3 size={12} /> {report.type}
                  </div>
                  <div>{report.size}</div>
                </div>

                <div className="flex items-center gap-2 mt-4 pt-4 border-t border-slate-100">
                  <div className={`px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-widest ${report.overallGrade === 'A+' ? 'bg-emerald-100 text-emerald-700 border border-emerald-200' :
                    'bg-slate-100 text-slate-700 border border-slate-200'
                    }`}>
                    {report.overallGrade}
                  </div>
                  <div className="text-xs text-slate-500 font-medium ml-auto">
                    {report.subjects.join(', ')}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Stats Preview */}
        <div className="p-12 rounded-xl] bg-gradient-to-br from-slate-50 to-slate-100 border border-slate-200 relative overflow-hidden">
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top_left,_var(--tw-gradient-stops))] from-blue-400/5 to-transparent" />
          <div className="relative z-10 grid lg:grid-cols-4 gap-8 text-center">
            <div>
              <div className="text-4xl font-black text-slate-900 mb-2">12</div>
              <div className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Reports Available</div>
            </div>
            <div>
              <div className="text-4xl font-black text-emerald-600 mb-2">97.5%</div>
              <div className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Avg Performance</div>
            </div>
            <div>
              <div className="text-4xl font-black bg-gradient-to-r from-blue-500 to-red-500 bg-clip-text text-transparent mb-2">A</div>
              <div className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Overall Grade</div>
            </div>
            <div>
              <div className="text-4xl font-black text-slate-900 mb-2">4.8/5</div>
              <div className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Faculty Rating</div>
            </div>
          </div>
        </div>
      </div>
    </DashboardLayout>
  );
}

